title: Hive Mirror Blog
description: Auto-published posts from @poprzeczka
author: racibo
url: https://racibo.github.io/hive-mirror-site
baseurl: /hive-mirror-site

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
